apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deploy
  labels:
    app: hello-app
    test: test
spec:
  selector:
    matchLabels:
      app: config-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
        - name: config-app-container
          image: martindarius/configimage:1.0.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 5050